datasets:
  census:
    column_mapping:
      categorical_features:
        - 'workClass'
        - 'education'
        - 'maritalStatus'
        - 'occupation'
        - 'relationship'
        - 'race'
        - 'sex'
        - 'nativeCountry'
      numerical_features:
        - 'age'
        - 'financialWeight'
        - 'educationNum'
        - 'capitalGain'
        - 'capitalLoss'
        - 'hoursPerWeek'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/adult-train.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
